# Site Settings
baseurl: ""
url : ""

# Blog Settings
theme_settings :
  title : Tosterius
  favicon : assets/favicon.png

  # Profile Settings
  profile :
    image : assets/img/ava.png
    username : Arthur Yalaletdinov
    description : Software engineer
    experience :
      - start : 2019-06
        end : now
        experience : Zhara music
      - start : 2017-09
        end : 2019-06
        experience : SpritDSP
      - start : 2017-09
        end : 2016-04
        experience : Aifil LCC
      - start : 2014-04
        end : 2015-07
        experience : Institute for System Programming of the Russian Academy of Sciences
    education :
      - start : 2006-09
        end : 2012-02
        education : Moscow State University, Mathematical Physics department
      - start : 2014-04
        end : 2015-07
        education : Institute for System Programming of the Russian Academy of Sciences
    skills : 
      - skill : Motivation
        value : 100  # Percent value
      - skill : C++
        value : 85  # Percent value
      - skill : Python
        value : 75  # Percent value
      - skill : Algorithms
        value : 75  # Percent value
      - skill : ML theory
        value : 75  # Percent value
        
  # Icons
  icons :
    email:  arthur.yal@yandex.ru
    linkedin: https://www.linkedin.com/in/arthur-yalaletdinov-0aaa1068/
    github: tosterius
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-paginate
  - jekyll-last-modified-at
bootstrap:
  assets: true

collections:
  notes:
    output: true
